var qa = {          
    "a":[
            ["Acqua","disseta gli assetati"],
            ["Andersen","a Copenhagen gli e' stata dedicata una Sirenetta"],
            ["Attinia","altro nome dell'anemone di mare"],
            ["Amedei","Amedeo, 'il fornaretto' idolatrato dai romanisti"],
            ["Acapulco","citta' messicana celebre per le sue spiagge"],
            ["Antartide","di quale continente il monte Vinson (5.150 mt.) e' il massiccio piu' alto"],
            ["Arancia","e' il frutto piu' conosciuto della famiglia delle rutacee"],
            ["Australia","e' il paese con piu' pecore"],
            ["Aorta","E' il piu' grande vaso sanguigno del corpo umano"],
            ["Amen","e' l'ultima parola della Bibbia"],
            ["Annapurna","fu la prima cima oltre gli 8.000 metri ad essere conquistata"],
            ["Alaska","fu pagata piu' di 7 milioni di dollari nel 1867 dagli Stati Uniti"],
            ["Agamennone","fu ucciso da Clitennestra"],
            ["Aborigeni","gli originari abitanti dell'australia"],
            ["Artificiali","i 'paradisi' di Baudelaire"],
            ["Amaro","il 'riso' di Giuseppe De Santis"],
            ["Angiolieri","il Cecco che si fece beffe del 'dolce stil novo'"],
            ["auriga","il cocchiere del carro da corsa nell'antica Roma"],
            ["Africa","il continente che comprende il maggior numero di nazioni"],
            ["Africa","il continente con la Sierra Leone"],
            ["Allah","il dio del quale porta il nome la perla piu' grossa del mondo"],
            ["Abbondio","il Don che camminava in una stradicciola nei pressi del lago di Como il 7 novembre 1628"],
            ["Arno","il fiume in cui Manzoni fece 'il bucato'"],
            ["Agamennone","il fratello di Menelao"],
            ["Arpino","il Giovanni che ha scritto La suora giovane"],
            ["Anquetil","il Jacques ciclista francese che ha vinto il Tour per quattro volte consecutive"],
            ["Anarchismo","il movimento politico fondato da Michail Bakunin"],
            ["Australia","il paese che ha accolto piu' di 75.000 forzati tra il 1750 e il 1840"],
            ["Ara","il pappagallo che ha le maggiori dimensioni"],
            ["Arthur AShe","il primo tennista di colore a vincere Wimbledon"],
            ["Ashe","il primo tennista di colore a vincere Wimbledon"],
            ["Avati","il Pupi regista italiano che ha fatto Una gita scolastica"],
            ["Agostino","il santo che ha scritto De civitate Dei"],
            ["Alcatraz","l'edificio che sorge su di uno scoglio della baia di San Francisco"],
            ["Aureliano","l'imperatore da cui prese il nome la citta' di Orleans"],
            ["Amleto","l'opera di Shakespeare nella quale i protagonisti muoiono quasi contemporaneamente"],
            ["Aida","l'opera di Verdi composta per l'inaugurazione dell'Opera del Cairo"],
            ["Abbey Road","l'ultimo album dei beatles"],
            ["Ambrosia","la bevanda degli dei dell'Olimpo"],
            ["Ande","la catena montuosa percorsa dalla linea ferroviaria piu' alta del mondo"],
            ["Amsterdam","la citta' in cui si trova il Dam"],
            ["Acqui","la citta' in cui si trova la cosiddetta Fontana miracolosa, con acqua minerale a 75 gradi"],
            ["Assuan","la diga che in Egitto ha permesso di strappare 800.000 ettari al deserto"],
            ["Anastasia","la figlia dello zar Nicola II che scampo' alla morte nel corso della rivoluzione russa"],
            ["Andrews","la Julie protagonista di Mary Poppins"],
            ["Agave","La pianta dalla quale si ricava la tequila"],
            ["Ancora","la porta tatuata Braccio di Ferro"],
            ["Alcazar","la reggia dei re mori a Siviglia"],
            ["Actor's Studio","la scuola nella quale si sono formati Marlon Brando e Robert De Niro"],
            ["Atletica","lo sport che deve il suo nome alla parola greca che significa 'combattimento'"],
            ["Automobilismo","lo sport in cui Emerson Fittipaldi e' stato campione del mondo"],
            ["Abolizionisti","negli Stati Uniti erano gli oppositori della schiavitu'"],
            ["Amigdala","parola che significa 'a forma di mandorla'"],
            ["Aruspici","prevedevano il futuro studiando le viscere degli animali"],
            ["anaerobico","processo che si svolge in assenza di ossigeno"],
            ["Abelardo","scambio' lettere d'amore con Eloisa"],
            ["Amarone","tipo di vino rosso del Veneto"],
            ["adenoidi","tonsille faringee"],
            ["Argentina","vi fu catturato Adolf Eichmann"],
            ["Aspromonte","vi provengono i pastori del romanzo del 1930 di Corrado Alvaro"],
            ["Australia","vi si trova il deserto di Simpson"],
            ["Antartide","vi si trova il mare di Ross"],                   
            ["Addizzione", "Operazione matematica"],
            ["Artificiali","'paradisi' di Baudelaire"],
            ["Arco", "arma con frecce"]
    ],
    "b":[                
            ["Bianco","e' il colore del lutto nei paesi musulmani"],
            ["Bardotto","e' il risultato dell'incrocio tra un cavallo e un asina"],
            ["Brasile","e' la quinta nazione piu' grande del mondo"],
            ["Beretta","hanno cominciato vendendo archibugi alla Serenissima e finito col vendere pistole all'FBI"],
            ["Bridge","il campionato del mondo vinto dal 'blue team' italiano"],
            ["Bacco","il dio del vino per i romani"],
            ["bianca","il film in cui Moretti (brrr) dice 'Come si fa a dormire con una donna con cui si e' fatto l'amore?'"],
            ["Buridano","il filosofo al quale si associa un asino morto di fame perche' incerto tra due cibi"],
            ["Bordin","il Gelindo primo italiano a vincere una maratona olimpica"],
            ["Bettega","il giocatore di calcio italiano che ha militato a fine carriera nei Toronto Blizzards"],
            ["Badminton","il gioco con le racchette apparso in Inghilterra verso il 1860"],
            ["Beach Boys","il gruppo formato dai fratelli Wilson nel 1961"],
            ["Baltico","il Mare che separa Riga da Stoccolma"],
            ["Bongiorno","il Mike che disse a una concorrente 'Ahi, ahi, signora Longari, mi e' caduta sull'uccello'"],
            ["Bongiorno","il Mike presentatore che fu condannato a morte per spionaggio nel 1944 da un tribunale militare tedesco"],
            ["Baracca","il pilota che aveva sull'aereo il cavallino rampante simbolo della Ferrari"],
            ["Barbarossa","il soprannome di Federico I imperatore germanico dal 1152 al 1190"],
            ["Bolscioi","il teatro del piu' famoso corpo di ballo di danza classica di Mosca"],
            ["Blueberry","il tenente disertore dell'esercito americano che e' un eroe dei fumetti"],
            ["Brandt","il Willy sindaco di Berlino Ovest che accolse J.F. Kennedy"],
            ["Bonsai","l'albero nano giapponese"],
            ["Bolena","l'Anna madre di Elisabetta I di Inghilterra"],
            ["Bouquet","l'aroma di un vino"],
            ["Boito","l'Arrigo librettista di Giuseppe Verdi che scrisse la musica di un'opera"],
            ["Boy-Scouts","l'associazione fondata dall'ufficiale britannico Robert Baden-Powell nel 1907"],
            ["Brando","l'attore che si rifiuto' di ritirare il secondo premio Oscar"],
            ["Bergman","l'attrice che ha debuttato nel 1938 con Intermezzo"],
            ["Bonaccorti","l'Enrica che divento' una star televisiva con la trasmissione Pronto, chi gioca?"],
            ["Bearzot","l'Enzo commissario tecnico della nazionale italiana vincitrice dei mondiali di calcio di spagna nel 1982"],
            ["Barletta","la 'Disfida' in cui gli italiani furono guidati da Ettore Fieramosca"],
            ["Baffi","la caratteristica facciale di Walt Disney che nessun altro collaboratore era autorizzato ad avere"],
            ["Brindisi","la citta' dalla quale Vittorio Emanuele III si imbarco' per lasciare definitivamente l'Italia"],
            ["Bruxelles","la citta' in cui fu organizzata l'esposizione universale del 1958"],
            ["Buenos Aires","la citta' in cui si trova la Casa Rosada"],
            ["Bouvier","la Jacqueline che ebbe J.F. Kennedy come primo marito"],
            ["Bronzo","la lega formata da rame e stagno"],
            ["Bose'","la Lucia protagonista del film di Maselli Gli sbandati"],
            ["Bianchina","la macchina di Fantozzi"],
            ["Butterfly","La Madama che si suicida con la sciabola del padre"],
            ["Bose","la Miss Italia che divenne una star del cinema e sposo' un famoso torero"],
            ["Bergamo","la provincia dove troviamo la casa di Arlecchino"],
            ["Bauhaus","la scuola tedesca di design e architettura diretta da Walter Gropius"],
            ["Bob","la slitta munita di volante con la quale si scende lungo piste ghiacciate"],
            ["Bernadette","la Soubirous a cui la Vergine Maria apparve a Lourdes"],
            ["Barbare","le 'Odi' del Carducci"],
            ["Bronte","le sorelle che scrivevano sotto gli pseudonimi di Currer, Ellis e Acton Bell"],
            ["Blue Jeans","li invento' Levi-Strauss"],
            ["Boraciferi","lo sono i soffioni di Larderello"],
            ["Baseball","lo sport americano che e' stato ammesso alle olimpiadi nel 1984"],
            ["Bhutto","lo Zulfikar Ali' impiccato in Pakistan nel 1979"],
            ["Bischero","parte di uno strumento a corde"],
            ["brina","Rugiada congelata"],
            ["Bolas","sono usate nelle pampas per catturare gli animali"],
            ["Bonn","vi nacque Ludwig Van Beethoven"]            
    ],
    "c":[                
            ["Copechi","100 formano un rublo"],
            ["Caliga","calzatura degli antichi soldati romani"],
            ["Carezza","celebre lago dolomitico che in tedesco si chiama Carersee"],
            ["Cagliari","citta' sarda in cui si celebra la festa di Sant'Efisio"],
            ["Caravaggio","cosi' era detto il pittore Michelangelo Merisi"],
            ["Carlomagno","era figlio di Pipino il Breve"],
            ["Corrado","era il conduttore della trasmissione radiofonica Rosso e nero"],
            ["Citroen","fabbrico' la prima auto a trazione anteriore"],
            ["Churchill","fu il Primo Ministro del regno di Elisabetta II di Inghilterra"],
            ["Carlomagno","fu incoronato imperatore nella notte di Natale dell'800"],
            ["Cleopatra","fu l'ultimo sovrano regnante della stirpe dei Tolomei"],
            ["Cagliari","fu la prima squadra di calcio a sud di Roma a vincere lo scudetto"],
            ["Cicerone","fu mortale avversario di Catilina"],
            ["Cartaginesi","furono sconfitti da Caio Duilio a Milazzo nel 260 a.C."],
            ["Cana","Gesu' vi compi' il miracolo della trasformazione dell'acqua in vino"],
            ["Chopin","ha composto 50 mazurche, 19 valzer e 14 polacche"],
            ["Cellini","ha scolpito la statua di Perseo che orna la loggia dei Lanzi a Firenze"],
            ["Colombo","ha scoperto la Giamaica"],
            ["Capillari","i piu' piccoli vasi sanguigni"],
            ["Castel del Monte","il castello a pianta e torrioni ottagonali che Federico II ha lasciato in Puglia"],
            ["Chaplin","il Charlie che ha realizzato L'opinione pubblica nel 1923"],
            ["Chaplin","il Charlie che ha sposato Oona O'Neill"],
            ["Cervi","il Gino che e' stato Ettore Fieramosca e Peppone"],
            ["Cervi","il Gino che interpretava Maigret"],
            ["Cousteau","il Jacques che esplorava le profondita' marine"],
            ["Clark","il Jim corridore soprannominato lo scozzese volante"],
            ["Chagall","il Marc che ha dipinto il soffitto dell'Opera di Parigi"],
            ["Calderone","il nome del ghiacciaio del Gran Sasso, unico di tutti gli appennini"],
            ["Canada","il paese che ha l'hockey su ghiaccio come sport nazionale"],
            ["Cina","il paese del panda gigante"],
            ["Cecoslovacchia","il paese invaso dalle truppe sovietiche nel 1968"],
            ["Chigi","il palazzo dove ha l'ufficio il primo ministro italiano"],
            ["Corriere della Sera","il quotidiano che ha sede in V. Solferino a Milano"],
            ["Casanova","il seduttore per antonomasia"],
            ["Carlo V","il sovrano sul cui impero il sole non tramontava mai"],
            ["Capitale","il suo primo volume e' 'Sviluppo della produzione capitalista'"],
            ["Cornamusa","il tipico strumento musicale degli scozzesi"],
            ["Ceylon","il vecchio nome dello Sri Lanka"],
            ["Cianidrico","l'acido che e' detto anche prussico"],
            ["Circo","l'ammaestratore di pulci ne e' il mestiere piu' faticoso per gli occhi"],
            ["Cammello","l'animale che forni' aiuto decisivo nelle campagne di Lawrence d'Arabia"],
            ["Coccodrillo","l'animale che si dice abbia rimorsi"],
            ["Cicala","l'animale che si esprime con 7.400 pulsazioni al minuto"],
            ["Che Guevara","l'Ernesto il cui cadavere fu esposto (brrr) dall'esercito boliviano nel 1967"],
            ["caracalla","l'imperatore che fece costruire a Roma il piu' famoso stabilimento termale"],
            ["Canossa","l'imperatore Enrico IV vi imploro' il perdono di Papa Gregorio VII"],
            ["Capri","l'imperatore Tiberio vi passava abitualmente le vacanze"],
            ["Cuba","l'isola piu' grande delle Antille"],
            ["Clouseau","l'ispettore interpretato da Peter Sellers"],
            ["Cicerone","l'oratore che svento' la congiura di Catilina"],
            ["Croce Rossa","l'organizzazione internazionale che ha vinto il solo premio Nobel assegnato durante la Prima Guerra Mondiale"],
            ["Cime tempestose","l'unico romanzo di Emily Bronte"],
            ["Chamberlain","l'uomo politico inglese che firmo' il patto di Monaco"],
            ["Calva","la 'cantatrice' di Ionesco"],
            ["Coca Cola","la bevanda alla quale corrisponde la formula segreta 7x"],
            ["Catania","la citta' con l'aeroporto Fontana Rossa"],
            ["Cnosso","la citta' cretese scoperta da Sir Arthur Evans"],
            ["Chaplin","La contessa di Honk Kong e' stato il suo ultimo film"],
            ["Athletics","la Gigliola che nel 1964 cantava Non ho l'eta'"],
            ["Cinquetti","la Gigliola che nel 1964 cantava Non ho l'eta'"],
            ["Chatterley","la Lady che fu l'amante del giardiniere"],
            ["Carie","la malattia non contagiosa piu' comune al mondo"],
            ["Curie","la Marie che ha vinto due premi Nobel"],
            ["Calipso","la ninfa che trattenne Ulisse per 10 anni"],
            ["Cartagine","la potenza nemica di Roma che disponeva di 5.000 navi"],
            ["Curie","la prima donna a vincere un premio Nobel"],
            ["Castelgandolfo","la residenza estiva del papa"],
            ["Chiara","la Santa protettrice di chi lavora in televisione"],
            ["Cosmos","la squadra statunitense in cui a fine carriera milito' Giorgio Chinaglia"],
            ["Continenti","li rappresentano i cinque cerchi olimpici"],
            ["Comune","lo e' la 'gente' per Robert Redford"],
            ["Cricket","lo sport dal quale deriva il baseball"],
            ["Calcio","lo sport piu' praticato al mondo"],
            ["Cipro","lo stato con Limassol"],
            ["Cromosfera","lo strato intermedio dell'atmosfera fra la fotosfera e la corona"],
            ["Coca Cola","nel 1886 veniva venduta per 5 cents a bicchiere dal signor Pemberton in una farmacia di Atlanta"],
            ["Costellazioni","nella nostra galassia ce ne sono 88"],
            ["caglio","si aggiunge al latte per ottenere il formaggio"],
            ["Cordless","telefono senza fili"],
            ["Clitennestra","uccise Agamennone"],
            ["Calais","una delle due citta' tra le quali si tenta generalmente la traversata della Manica a nuoto"],
            ["Cantonese","una delle grandi scuole in cui si divide la cucina cinese"],
            ["Caio","uno dei Gracchi"],
            ["Chicago","vi nacque l'associazione Rotary"],
            ["Courmayeur","vi si prende la funivia in Italia per ammirare la Mer de Glace"],
            ["Canada","vi si trova il polo nord magnetico"],
            ["Camelot","vi si trovava la corte di Re Artu'"]

    ],
    "d":[                
            ["Dispepsia","difficolta' di digestione"],
            ["Domenica","era 'd'agosto' per il regista Luciano Emmer"],
            ["Dayan","era ministro della difesa israeliano durante la guerra dei sei giorni"],
            ["Dante","ha scritto la vita nuova"],
            ["Diamante","il campo del Baseball"],
            ["de Mille","il Cecil B. che ha diretto una versione muta e una sonora de I dieci comandamenti"],
            ["Darwin","il Charles che sollevo' uno scandalo con La teoria dell'evoluzione"],
            ["D","il cognome di 'Umberto' in un film di De Sica"],
            ["Damocle","il cortigiano di Dionigi il Vecchio al quale fu sospesa una spada sul capo"],
            ["Dore'","il Gustave incisore francese che ha illustrato Don Chisciotte, Divina commedia, Bibbia e l'Orlando furioso"],
            ["Dunlop","il John che ha inventato il pneumatico"],
            ["Daguerre","il Luis che scopri' il procedimento di sviluppo delle immagini fotografiche"],
            ["dieci","il numero di carte che si danno a ciascun giocatore nel tressette"],
            ["Danimarca","il paese il cui territorio e' costituito principalmente dalla penisola dello Jutland"],
            ["Delon","interpreta un pugile in Rocco e i suoi fratelli"],
            ["Durer","l'Albrecht pittore tedesco de I quattro apostoli"],
            ["Delfino","l'erede al trono francese"],
            ["Duncan","l'Isadora che fece scandalo ballando a piedi nudi"],
            ["Deneuve","la Catherine Bella di giorno"],
            ["Dum-Dum","la citta' indiana che ha dato il nome a proiettili da fucile"],
            ["Dietrich","la Marlene 'angelo azzurro'"],
            ["Dorate","le ali del 'pensiero' di Verdi"],
            ["dirigibile","lo fu l'Hindenburgh"],
            ["Divorzio","ottenne il voto favorevole del 60% degli italiani il 13 maggio 1974"],
            ["daga","Spada corta e larga a due tagli"]

    ],   
    "e":[                
            ["Edipo","Accecato, fu guidato da Antigone"],
            ["Epifisi","altro nome della ghiandola pineale"],
            ["Eisenhower","comandava le forze armate alleate durante lo sbarco in Normandia"],
            ["Elisir di lunga vita","diceva di possederlo il Conte di Saint Germain"],
            ["Edonismo","dottrina che ha come principio la ricerca del piacere"],
            ["Emofilia","e' la malattia dei re"],
            ["Eleganza","il campo nel quale dettava legge Lord Brummel"],
            ["Eschilo","il drammaturgo greco che si dice sia morto colpito da una tartaruga lasciata cadere da un aquila in volo"],                
            ["errore","Non si deve cadere due volte nello stesso..."],
            ["Ellington","il Duke 'duca' del jazz"],
            ["Ezechiele","il lupo che da la caccia ai tre porcellini"],
            ["Ewan","Il nome dell'attore McGregor"],
            ["Enrico VIII","il padre di Elisabetta I di Inghilterra"],
            ["Ecuador","il paese al quale appartengono le Galapagos"],
            ["Eldorado","il paese d'oro cercato dai conquistatori spagnoli"],
            ["Ermitage","il palazzo fatto costruire a Pietroburgo da Caterina II che e' oggi un museo"],
            ["Elfi","il popolo sul quale regnava Oberon"],
            ["Einstein","l'Albert che disse 'Dio non gioca a dadi'"],
            ["Esegesi","l'interpretazione di un testo"],
            ["Evita","la commedia musicale dalla quale e' tratta la canzone Don't cry for me Argentina"],
            ["Euratom","la comunita' europea dell'energia atomica"],
            //["banana yoshimoto","la comunita' europea dell'energia atomica"],
            ["Eucalipto","la pianta delle cui foglie si nutre il koala"],
            ["Eclittica","la traiettoria apparente del sole in un anno"],
            ["Equitazione","lo sport al quale appartiene l'espressione 'mezza volta'"],
            ["Equitazione","lo sport olimpico in cui donne e uomini gareggiano alla pari"],
            ["Eloisa","scambio' lettere d'amore con Abelardo"],
            ["Etologia","scienza che studia il comportamento degli animali"],
            ["Emirati Arabi Uniti","sono formati da Abu Dhabi, Dubai, Sharjah, Ajman, Umm al Quaiwain, Ras al-Khaimah e Fujayrah"],
            ["Enrico II","sposo' Caterina de Medici"],
            ["Esau'","vendette il suo diritto di primogenitura per un piatto di lenticchie"],
            ["Eton","vi si trova la piu' celebre Public school inglese fondata da Enrico VI"]

    ],   
    "f":[                
        ["Formica","animale che per la Bibbia e' simbolo di saggezza"],
        ["Fotodiodo","Componente elettronico capace di entrare in conduzione solo se colpito da luce"],
        ["Fornarina","cosi' era soprannominata la figlia di un panettiere romano amata da Raffaello"],
        ["Filippo II","creo' l'Invincibile Armada"],
        ["Fedra","figlia di Minosse e sorella di Arianna"],
        ["Fellini","giro' Le notti di Cabiria"],
        ["Fossa delle Marianne","ha una profondita' di circa 11.000 m."],
        ["Fracassa","il 'Capitan' soprannome del barone di Sigognac"],
        ["Fosse","il Bob che ha realizzato Cabaret e All that jazz"],
        ["Faraday","il Michael che ha dato il suo nome a una 'gabbia' e a un 'cilindro'"],
        ["Falklands","il nome britannico delle Isole Malvine"],
        ["Filogamo","Il Nunzio che salutava i Cari amici vicini e lontani"],
        ["Firenze","città del campanile di Giotto"],
        ["Fangio","il pilota argentino che ha vinto 5 titoli mondiali di F1"],
        ["Fanfani","il primo presidente del consiglio a installarsi a Palazzo Chigi"],
        ["Fra Diavolo","il soprannome del bandito Michele Pezza"],
        ["Flynn","l'Errol che ha interpretato Robin Hood sul grande schermo"],
        ["Fieramosca","l'Ettore che guido' gli italiani nella Disfida di Barletta"],
        ["femore","l'osso piu' lungo del corpo umano"],
        ["Furtiva","la 'lacrima' di Donizetti"],
        ["fanfara","la banda dei bersaglieri"],
        ["Foglie","la parte dell'albero in cui avviene la fotosintesi clorofilliana"],
        ["Farnesina","La sede del Ministero degli Esteri"],
        ["Ferrari","la vettura con la quale Niki Lauda e' stato per due volte campione del mondo"],
        ["Falsario","lo era Gianni Schicchi, nominato da Dante nel suo Inferno"],
        ["Fangio","pilota che vinse 4 campionati mondiali consecutivi in F1"],
        ["Federico II","re prussiano del XVIII secolo considerato un esempio di 'despota illuminato'"]

    ],   
    "g":[                
            ["Gordio","Alessandro Magno ne taglio' con la spada l'inestricabile nodo"],
            ["Gravina","Carla, prima attrice italiana a diventare deputato"],
            ["Gomorra","Citta' della Palestina che secondo Mose' fu distrutta per i suoi vizi da un incendio"],
            ["Gatsby","e' 'Grande' nel romanzo di Francis Scott Fitzgerald"],
            ["Ginevra","era la moglie di re Artu' e l'amante di Lancillotto"],
            ["Giorgio VI","era re di Inghilterra durante la seconda guerra mondiale"],
            ["Giotto","fece il campanile del duomo di Firenze"],
            ["Garibaldi","fu definito dal Carducci 'novello Romolo'"],
            ["Girardengo","fu spodestato da Binda dal trono del ciclismo italiano"],
            ["Goodyear","ha scoperto la vulcanizzazione del caucciu'"],
            ["Gable","il Clark di Via col vento"],
            ["Grimaldi","il cognome da ragazza di Carolina di Monaco"],
            ["Giano","il dio romano dal quale gennaio prende il nome"],
            ["Gershwin","il George che ha composto Porgy and Bess"],
            ["Gershwin","il George che ha composto Summertime"],
            ["Giancattivi","il gruppo del quale faceva parte Francesco Nuti"],
            ["Gandhi","il leader cremato il 31 gennaio 1948 sulle rive del Gange"],
            ["Gaye","il Marvin cantante ucciso dal padre a colpi di pistoia"],
            ["Giovanna","il nome dell'unica donna che, secondo una leggenda medievale, sia stata assunta al soglio pontificio"],
            ["Gargantua","il padre di Pantagruel"],
            ["Grecia","il paese dell'ouzo"],
            ["Goya","il pittore spagnolo che fece 'i capricci'"],
            ["Giapponese","il popolo che ha un alfabeto di 28.000 simboli"],
            ["Genesi","il primo libro dell'Antico Testamento"],
            ["Giona","Il profeta ingoiato da una balena"],
            ["Gallina","il volatile piu' diffuso della terra"],
            ["Guinness","l'Alec che ha interpretato otto personaggi nel film Sangue blu"],
            ["Ghepardo","l'animale che e'uo' raggiungere i 101 km/h"],
            ["Gramsci","l'Antonio fondatore del PCI (brrr) sepolto nel cimitero degli inglesi a Roma"],
            ["Giuliano","L'Apostata che mori' dicendo 'Hai vinto, Galileo'"],
            ["Giovenale","l'autore del famoso verso latino 'Mens sana in corpore sano'"],
            ["Gesuiti","l'ordine fondato da Ignazio di Loyola"],
            ["Grog","la bevanda a base di alcol che ha la fama di curare il raffreddore"],
            ["Giumenta","la cavalla da sella"],
            ["Gibilterra","la colonia britannica che e' soprannominata 'la rocca'"],
            ["Gibilterra","la colonia britannica che ha una superficie di soli 6 km quadrati"],
            ["Galateo","la famosa opera di Monsignor Della Casa"],
            ["Gotta","la malattia detta anche podagra"],
            ["Gala","la modella preferita da Salvador Dali'"],
            ["Godot","lo aspettava Samuel Beckett"],
            ["Goethe","lo scrittore tedesco che ha descritto nelle sue opere piu' di 2.000 paesaggi, dei quali circa la meta' italiani"],
            ["Gioia","Melchiorre, noto economista dell'800 considerato il fondatore della statistica in Italia"]

    ],   
    "h":[                
            ["Hammet","il Dashiell autore de Il falcone maltese"],
            ["Heathcliff","il protagonista di Cime tempestose"],
            ["Harlem","il quartiere nero di New York"],
            ["Hill","il Terence che Continuavano a chiamarlo Trinita'"],
            ["Herrera","l'allenatore dell'inter Campione d'Europa nel 1964 e 1965"],
            ["Harvard","l'universita' di Love Story"],
            ["Hashish","la sostanza che permetteva a Baudelaire di raggiungere i paradisi artificiali"],
            ["Hertziane","le onde di cui si servi' Alessandro Marconi per il telegrafo senza fili"]              
    ],
    "i":[
        ["Ipofisi","altro nome della ghiandola pituitaria"],
        ["idromele","Bevanda a base di acqua e miele"],
        ["Istanbul","era una delle citta' collegate dall'Orient Express"],
        ["Islanda","fu il primo paese a legalizzare l'aborto nel 1935"],
        ["Insetti","Gli animali piu' antichi"],
        ["Incompreso","il film di Comencini che racconta la predilezione di un padre per il figlio cadetto"],
        ["Ippolito","il Nievo di Confessioni di un ottuagenario"],
        ["Ippocrate","l'antico greco ritenuto il padre della medicina"],
        ["Ikebana","l'arte floreale giapponese"],
        ["Insalata","l'aveva Marameo nell'orto"],
        ["Internazionale","l'Intrigo per il quale Cary Grant viene mitragliato da un aeroplano"],
        ["Indiana","la bandiera che sventola su Mysore e Madras"],
        ["Inglese","la bandiera che sventola su un promontorio tra Cadice e Malaga"],
        ["Irish","la I della sigla I.R.A."],
        ["Iride","la membrana che controlla la quantita' di luce che entra nell'occhio"],
        ["Inglese","la seconda lingua piu' parlata al mondo"],
        ["Israele","lo stato col deserto del Negev"],
        ["Indiana","lo stato in cui si corrono le 500 miglia di Indianapolis"],
        ["Israele","lo stato in cui si trova il porto di Haifa"],
        ["Ibisco","vi si ricava il carcade'"]
    ],
    "l":[
        ["Los Angeles","La città degli Angeli d'oltre Oceano"],
        ["Londra","la città con l'Abbazia di Westminster"],
        ["Lake Placid","citta' degli Usa che ha ospitato per due volte le olimpiadi invernali"],
        ["luppolo","Conferisce alla birra l'inconfondibile gusto amarognolo"],
        ["Leone","E' l'unico felino a condurre una vita sociale"],
        ["Lassie","il cane piu' celebre di Hollywood"],
        ["Laughton","il Charles protagonista del film Le sei mogli di Enrico VIII"],
        ["Locarno","il festival del cinema che premia con il Leopardo d'oro"],
        ["Lemond","il Greg che e' stato il primo americano a vincere un campionato di ciclismo su strada"],
        ["Lewis","Il Jerry 'ragazzo tuttofare' idolo delle donne"],
        ["Lorenz","il Konrad che e' stato una seconda mamma per le anatre"],
        ["Lemano","il lago sul quale si trova Ginevra"],
        ["C.C.C.P.","il poeta latino che conosceva La natura delle cose"],
        ["Longobardi","il popolo del quale fu regina Rosamunda"],
        ["Lothar","l'aiutante di Mandrake"],
        ["Lucifero","l'angelo che precipito' dal cielo"],
        ["Lombard","la Carole che con Clark Gable formava la coppia ideale di Hollywood"],
        ["Londra","la citta' del Covent Garden"],
        ["Las Vegas","la citta' dove si disputano ogni anno i campionati mondiali di poker"],
        ["Londra","la citta' servita dall'aeroporto di Gatwick"],
        ["Lancia","la fabbrica dell'Aurelia"],
        ["Lockheed","la fabbrica di aeroplani americana che ha coinvolto in uno scandalo l'allora premier giapponese Tanaka"],
        ["Lollobrigida","La Gina che e' la piu' famosa figlia di Subiaco"],
        ["Lammermoor","la Lucia di Donizetti"],
        ["Lotus","La macchina con la quale Jim Clark ha vinto le 500 miglia di Indianapolis"],
        ["Lussuria","La simboleggia la lonza, una delle tre belve che sbarrano il passo a Dante"],
        ["Liala","Lo pseudonimo con il quale e' meglio conosciuta la scrittrice Liliana Negretti Cambiasi"],
        ["Liverpool","vi si trova Penny Lane"]
    ],
    "m":[
        ["Milano","La città con la Madonnina"],
        ["Marco Antonio","contese a Cesare l'amore di Cleopatra"],
        ["Magellano","dette il nome all'Oceano Pacifico"],
        ["Marx","disse 'La religione e' l'oppio dei popoli' (brrr)"],
        ["Mendel","e' considerato il padre della genetica"],
        ["Mediterraneo","e' il 'mare nostrum'"],
        ["Mulo","e' il risultato dell'incrocio tra un asino e una cavalla"],
        ["Magnani","era madre di una figlia 'Bellissima'"],
        ["Minosse","Figlio di Zeus e padre di Arianna, re di Creta"],
        ["Mussolini","fu liberato da un commando tedesco a Campo Imperatore"],
        ["Malagodi","ha guidato il Partito Liberale dal 1954 al 1972"],
        ["Mazzola","il 'baffo' del calcio italiano"],
        ["Meraviglioso","il 'mandarino' di Bela Bartok"],
        ["Mangiafuoco","il burattinaio di Pinocchio"],
        ["Moby Dick","il caposaldo della letteratura americana che comincia con le parole 'Mi chiamo Ishmael'"],
        ["Mendeleev","il chimico russo che classifico' gli elementi secondo il loro peso atomico"],
        ["Magna Charta","il documento imposto a Giovanni Senza Terra dai feudatari inglesi"],
        ["MacArthur","il Douglas che comandava le truppe delle Nazioni Unite all'inizio della guerra di corea"],
        ["muleta","Il drappo rosso dei toreri"],
        ["Marinetti","il Filippo Tommaso principale figura letteraria del movimento futurista"],
        ["Missing","il film di Costa Gavras che ha come interpreti Jack Lemmon e Sissy Spacek"],
        ["metropolis","il film in cui compaiono 25.000 uomini, 11.000 donne e 1.100 calvi"],
        ["Menelao","il fratello di Agamennone"],
        ["Mozart","il genio della musica che e' finito in una fossa comune"],
        ["Murat","il Gioacchino fucilato a Pizzo Calabro"],
        ["Morandi","il Giorgio pittore italiano famoso per le sue bottiglie"],
        ["Miller","il Glenn che ha composto Moonlight Serenade"],
        ["Maggiore","il lago con le isole Borromee"],
        ["Monet","il leader del movimento impressionista nella pittura a Parigi"],
        ["Mediterraneo","il mare che bagna Barcellona"],
        ["Menelao","il marito della bella Elena"],
        ["Mercurio","il metallo piu' pesante"],
        ["Milva","il nome d'arte di Maria Ilva Biolcati"],
        ["Mailand","il nome tedesco di Milano"],
        ["Marocco","il paese africano in cui la stessa famiglia regna dal 1640"],
        ["Messico","il paese dal quale si innalza il Popocatepetl"],
        ["Monaco","il paese sul mare che ha il piu' piccolo litorale al mondo"],
        ["Marlowe","il Philip interpretato da Humphrey Bogart ne Il grande sonno"],
        ["Melanina","il pigmento cutaneo responsabile dell'abbronzatura"],
        ["Magritte","il pittore che con una sua opera ha ispirato il titolo del film Le fate ignoranti"],
        ["Manhattan","il quartiere centrale di New York"],
        ["Municipio","in tedesco viene chiamato Rathaus"],
        ["Musica","l'arte nella quale si hanno 'accidenti' e 'acciaccature'"],
        ["Moses","L'Edwin che vince 90 gare consecutive tra il 1977 e il 1984"],
        ["Miller","L'Henry autore di Sexus, Plexus e Nexus"],
        ["Monrovia","la capitale africana che deve il suo nome a un presidente Usa"],
        ["Madrid","la capitale della Puerta del Sol"],
        ["Marmore","la cascata formata dal Velino"],
        ["My Fair Lady","la commedia musicale di George Cukor che ha come interpreti Audrey Hepburn e Rex Harrison"],
        ["Maratona","la corsa che si effettua su 42km e 195 m."],
        ["Masina","la Giulietta degli spiriti"],
        ["Malaria","la malattia di cui e' portatrice la zanzara anofele"],
        ["Memoria","la qualita' che dette fama mondiale a Pico della Mirandola"],
        ["Milan","la squadra del trio Gre-No-Li"],
        ["Milan","la squadra di calcio in cui giocavano il Pompiere, il Professore e il Barone"],
        ["Mose'","la statua di Michelangelo che si trova in S. Pietro in Vincoli"],
        ["Miss Marple","la vecchia investigatrice famosa quanto Hercule Poirot"],
        ["Matteo","lo era 'secondo..' il vangelo di Pasolini"],
        ["mangusta","mortale nemico del cobra"],
        ["Mangusta","piccolo mammifero carnivoro utilizzato per lo sterminio dei rettili"],
        ["Monopoli","popolare gioco da tavolo dal tabellone composto da 40 caselle"],
        ["Matusalemme","secondo la Bibbia visse in piena forma fino a 969 anni"],
        ["Moravia","sposo' Carmen Llera sulla soglia degli 80 anni"],
        ["Motore","vi si trova l'albero a camme"],
        ["Mennea","vinse l'oro nei 200 metri piani alle olimpiadi di Mosca"],                
        ["matricidi","Gli assassini come Edipo"]
    ],
    "n":[
        ["Noci","I frutti con il mallo e il gheriglio"],
        ["Nebbia","e' formata da minuscole gocce e pulviscolo atmosferico"],
        ["Nostradamus","era l'astrologo di Maria de' Medici"],
        ["Neto","fiume della Calabria"],
        ["Nemo","il comandante del Nautilus"],
        ["No","il Dottor nemico di Sean Connery con licenza di uccidere"],
        ["Nigeria","il paese piu' popoloso dell'Africa"],
        ["Nasser","il presidente egiziano che nazionalizzo' il canale di Suez"],
        ["Nadir","il punto del cielo sulla verticale dell'osservatore, lungo una retta passante per il centro della terra"],
        ["Nautilus","il sottomarino atomico che e' passato per primo sotto l'intera la calotta polare artica"],
        ["Numero di Avogadro","indica il numero di molecole di qualsiasi sostanza"],
        ["Nomentana","l'antica via romana che parte da Porta Pia"],
        ["Napoleone","l'imperatore che ha scritto Dialogo sull'amore"],
        ["Newton-John","l'Olivia partner di Travolta in Grease"],
        ["Niemeyer","l'Oscar architetto di Brasilia"],
        ["Napoleone","l'ultimo periodo del suo regno fu detto 'i cento giorni'"],
        ["nuziale","la famosa 'marcia' composta da Mendelssohn"],
        ["Nastassia","la figlia di Klaus Kinski"],
        ["Naumachie","le battaglie navali organizzate come spettacoli dagli antichi romani"],
        ["Nietzsche","lo scrittore che elaboro' il concetto di Superuomo"],
        ["Nanosecondo","miliardesimo di secondo"],
        ["Napoleon","rinomato cognac francese"],
        ["Napoli","vi si svolge annualmente la Festa dei Gigli"]
    ],
    "o":[
        ["Orsi","Dino Buzzati ne ha descritto l'invasione in Sicilia"],
        ["Orgoglio","e' con il 'pregiudizio' in un romanzo di Jane Austin"],
        ["Ob","fiume russo che scorre in Siberia e si getta nel mar di Kara"],
        ["Ottano","idrocarburo che presenta 8 atomi di Carbonio"],
        ["Owens","il Jesse pantera nera dell'atletica"],
        ["Ornitorinco","il mammifero che ha zampe palmate e unghiute e depone le uova"],
        ["Orleans","la battaglia nella quale Giovanna D'Arco comando' le truppe francesi"],
        ["Oslo","la citta' nella quale si puo' ammirare il Kon-Tiki"],
        ["oligominerali","le acque che contengono fino a 1/2 grammo di sali per litro"],
        ["Oscar","premio che fu assegnato per la prima volta nel 1929"],
        ["Onore","vi fu ferito Mimi' Metallurgico"],
        ["Ostia","vi fu ucciso Pier Paolo Pasolini"]
    ],
    "p":[
        ["Parigi","La città con la cattedrale di Notre Dame"],
        ["Paese","Lo e, secondo un detto, tutto il mondo"],
        ["Pepe'","'le Moko' di Julien Duvivier"],
        ["Parche","a Roma erano le divinita' del destino"],
        ["Plasmodio","agente della malaria"],
        ["punch","Bevanda calda a base di rum, zucchero, te', cannella, scorza di limone"],
        ["Planisfero","Carta geografica che rappresenta l'intera superficie terrestre"],
        ["Pi greco","corrisponde a 3,14159"],
        ["Pitone","e' il serpente piu' lungo"],
        ["Piacere","e' ricercato dall'epicureo"],
        ["Pitagora","e' suo il teorema del quadrato dell'ipotenusa"],
        ["Pele'","era chiamato 'la perla nera'"],
        ["Pave'","fa sobbalzare i ciclisti nella Parigi-Roubaix"],
        ["Peripatetici","i discepoli di Aristotele"],
        ["Polders","i terreni 'rubati' al mare dei paesi bassi"],
        ["Pontecorvo","il Bruno scienziato italiano protagonista nel 1950 di una clamorosa fuga all'est"],
        ["Pizarro","il conquistatore dell'impero Inca"],
        ["Pratt","il creatore di Corto Maltese"],
        ["Pierre","il de Coubertin che contribui' alla rinascita delle Olimpiadi nell'era moderna"],
        ["presbiopia","il difetto della vista di chi non vede bene da vicino"],
        ["Pandoro","il dolce di Verona"],
        ["Papageno","il fidanzato di Papagena de Il flauto magico"],
        ["Pele'","il giocatore che ha disputato con 12 anni di intervallo due finali della Coppa del mondo di calcio"],
        ["Pol Pot","il leader dei Khmer rossi"],
        ["Pescatore","il mestiere dei protagonisti de La terra trema"],
        ["Pescatori","il mestiere dei protagonisti de La terra trema"],
        ["Pantheon","il monumento di Piazza della Rotonda a Roma"],
        ["Parigi","il nome moderno di Lutetia"],
        ["Pipino il Breve","il padre di Carlomagno"],
        ["Polonia","il paese invaso dai tedeschi il 1 settembre del 1939"],
        ["Powell","il Robert che ha interpretato il Gesu televisivo di Zeffirelli"],
        ["Polanski","il Roman di Chinatown"],
        ["Peckinpah","il Sam che ha fatto il Mucchio selvaggio"],
        ["pesce","il simbolo dei primi cristiani"],
        ["Pozzo","il Vittorio commissario tecnico della squadra vincitrice dei campionati del mondo di calcio 1934 e 1938"],
        ["Pulce","l'animale che al meglio della forma puo' saltare fino a 0,20 mt."],
        ["Picasso","l'artista che e' riuscito a vendere le proprie opere esposte al Louvre"],
        ["Luigi Pirandello","l'autore di Uno, nessuno, centomila"],
        ["Prana","l'energia dei guaritori"],
        ["Processo","l'opera di Kafka dalla quale Orson Welles ha tratto un film"],
        ["Parassita","l'organismo che vive alle spalle di un altro"],
        ["Piemontese","l'origine che accomuna Coppi, Bettega e Pavese"],
        ["Parsifal","l'ultima opera di Wagner"],
        ["Pantheon","la chiesa di Roma dove e' sepolto Raffaello"],
        ["Parigi","la citta' dove possiamo prendere un te' al Caffe' de la Paix"],
        ["Parma","la citta' italiana che e' circondata da uno 'stradone'"],
        ["Pahlevi","la dinastia che ha regnato in Iran dal 1921 al 1979"],
        ["Papagena","la fidanzata di Papageno de Il flauto magico"],
        ["Parisi","la Heather ballerina scoperta in una discoteca dal coreografo Franco Miseria"],
        ["Portoghese","la lingua ufficiale dell'isola di Capo Verde"],
        ["Porsche","la macchina al volante della quale ha trovato la morte James Dean"],
        ["Palermo","La provincia con l'isola di Ustica"],
        ["Piacenza","La provincia dell'Emilia Romagna piu' vicina alla Lombardia"],
        ["Pece","la resina del calzolaio"],
        ["Paleontologia","la scienza che studia i fossili"],
        ["peripatetica","la scuola fondata da Aristotele ad Atene"],
        ["Postalmarket","la societa' che per prima in Italia ha effettuato la vendita per corrispondenza"],
        ["Porro","la verdura che e' l'emblema del Galles"],
        ["Penati","le divinita' romane che proteggevano i focolari"],
        ["prefiche","le donne dell'antica grecia pagate per piangere ai funerali"],
        ["Puniche","le guerre che opposero Roma a Cartagine"],
        ["Padrino","lo e' Don Vito Corleone"],
        ["Paleografia","lo studio delle scritture antiche"],
        ["Peso","moneta argentina"],
        ["Pico","quello della Mirandola divento' famoso per la memoria prodigiosa"],
        ["Pandora","satellite di Saturno"],
        ["Perseidi","sono chiamate 'Lacrime di San Lorenzo'"],
        ["75","Ulisse e i compagni fuggirono dalla grotta di Polifemo attaccati al loro ventre"],
        ["Pecore","Ulisse e i compagni fuggirono dalla grotta di Polifemo attaccati al loro ventre"],
        ["Pechinese","una delle grandi scuole in cui si divide la cucina cinese"],
        ["Piemonte","uno dei due piroscafi usati per la spedizione dei mille"]

    ],
    "q":[
        ["Quercia","il legno delle botti in cui invecchia il vino di Bordeaux"],
        ["Queen Elizabeth","il piu' grande transatlantico mai costruito"],
        ["Quarto","la localita' dalla quale salparono i mille"],
        ["Quant","la Mary che negli anni '60 ha scoperto le ginocchia alle donne"],
        ["Quasimodo","Salvatore poeta ermetico italiano"]
    ],
    "r":[
        ["Roma","La citta con la Basilica di S.Pietro"],
        ["Ricotta","costituisce il ripieno dei cannoli alla siciliana"],
        ["Reagan","e' stato il 42esimo presidente degli Stati Uniti"],
        ["Rin Tin Tin","il cane di Hollywood morto tra le braccia di Jean Harlow nel 1932"],
        ["Ronzinante","il cavallo di Don Chisciotte"],
        ["Romanov","il cognome di Nicola II ultimo zar di russia"],
        ["Rivera","il Gianni 'golden boy' del calcio italiano"],
        ["Riva","il Mario televisivo che mori' nel 1960 cadendo da un'impalcatura dell'Arena di Verona"],
        ["Roosevelt","il presidente statunitense che diede il via al New Deal"],
        ["Reticolo","il secondo stomaco dei ruminanti"],
        ["Riso","l'alimento che e' quello base per il 54% della popolazione terrestre"],
        ["Revolver","l'arma inventata da Samuel Colt"],
        ["Rondine","l'uccello famoso per la sua particolare cura del nido"],
        ["Rio de Janeiro","la capitale del Brasile fino al 1960"],
        ["Rieti","la citta' dell'alto Lazio che diede a Roma tre imperatori"],
        ["Ravenna","la citta' settentrionale italiana che e' stata capitale dell'impero d'Occidente"],
        ["Rimet","la coppa che premiava i campioni del mondo di calcio fino al 1970"],
        ["Reynolds","la Debbie partner di Gene Kelly in Cantando sotto la pioggia"],
        ["Ross","la Diana che ha debuttato con le Supremes"],
        ["Republican","la R della sigla I.R.A."],
        ["Roulette","la ruota inventata da Pascal nella ricerca del movimento perpetuo"],
        ["Rindt","lo Jochen diventato campione di F1 dopo la morte"],
        ["Rolls-Royce","sono le auto di serie piu' costose al mondo"]
    ],
    "s":[
        ["Svastica","altro nome della croce uncinata"],
        ["Sharks","con i Jets e' una delle bande rivali di West Side Story"],
        ["Sultanina","cosi' e chiamata l'uva passa"],
        ["Sinottici","cosi' sono stati chiamati i Vangeli di Marco, Luca e Matteo per la loro grande affinita'"],
        ["Silenzio","e' 'd'oro' quello di Rene' Clair"],
        ["Stella","e' 'nata' in un film di George Cukor"],
        ["Scimpanze'","e' il piu' intelligente tra gli antropoidi"],
        ["Siviglia","Figaro vi aveva la sua bottega"],
        ["Senso","film di Visconti in cui Farley Granger e Alida Valli vivono una tragica storia d'amore"],
        ["Sublicio","fu il primo ponte sul Tevere costruito dai Romani"],
        ["Savoia","furono proprietari della Sacra Sindone fino al 1983"],
        ["Serpenti","gli animali che danno il nome alla caratteristica processione di Cocullo"],
        ["Salomone","gli rese visita la Regina di Saba"],
        ["Shaw","il Bernard che disse 'La sigaretta e' un rotolino di carta con ad un'estremita' un fuoco e all'altra uno sciocco'"],
        ["Sonni","Chi è onesto, li dorme tranquilli.."],
        ["Springsteen","il Bruce detto The boss"],
        ["Suez","il canale che inizia a Porto Said"],
        ["Sombrero","il caratteristico copricapo messicano"],
        ["Sandinismo","il movimento rivoluzionario al quale ha dato vita il 'generale dei poveri' Cesare Sandino in Nicaragua"],
        ["Sublicio","il ponte romano sul quale Orazio Coclite respinse un attacco degli etruschi di Porsenna"],
        ["Spielberg","Il regista del film A.I.- Intelligenza Artificiale"],
        ["Spermatozoo","il ruolo interpretato da Woody Allen nell'ultimo episodio del film Tutto quello che avreste voluto sapere sul sesso..."],
        ["Scarface","il soprannome di Al Capone"],
        ["Sheridan","il tenente interpretato da Ubaldo Lay"],
        ["Schweitzer","l'Albert che nel tempo libero suonava l'organo"],
        ["Squalo","l'animale allevato vicino alle basi aeronavali per tenere lontani gli uomini rana"],
        ["scarabeo","l'animale venerato dagli egizi come simbolo del Sole"],
        ["Stagno","l'elemento principale del peltro"],
        ["Salgari","l'Emilio che scrisse mirabolanti avventure esotiche senza mai andare all'estero"],
        ["Scacchi","l'incontro nel quale i contendenti hanno due cavalli ciascuno"],
        ["Spagnola","l'influenza che nel 1918 provoco' 20 milioni di morti"],
        ["Swann","la 'strada' con la quale inizia Alla ricerca del tempo perduto"],
        ["Saint Moritz","la citta' svizzera che ha ospitato due volte le Olimpiadi invernali"],
        ["Surrealismo","la corrente artistica di Magritte"],
        ["Starnuto","la funzione corporale che provoca una velocita' di 600 km/h"],
        ["Sanscrito","la lingua dalla quale ha origine la parola 'yoga'"],
        ["Schneider","la Maria che ha ballato l'Ultimo tango con Marlon Brando"],
        ["Stuarda","la Maria che ha ereditato il trono di Scozia all'eta' di sei giorni"],
        ["Spagnola","la nazionalita' degli abitanti dell'isola di Formentera"],
        ["Stilografica","la penna inventata da Lewis A. Waterman"],
        ["Sardegna","la regione dei 'quattro mori'"],
        ["Scintoismo","la religione piu' diffusa in Giappone"],
        ["Serpentino","la roccia la cui massa verde e' striata di bianco"],
        ["Schneider","la Romy che ha interpretato Sissi"],
        ["Simpson","la Wallis che Edoardo VIII chiamava 'la donna che amo'"],
        ["sherpa","le guide di montagna nepalesi"],
        ["Superstar","lo diventa Gesu' Cristo in una nota commedia musicale"],
        ["Surf","lo sport che un tempo era riservato alle famiglie reali delle Hawaii"],
        ["Scherma","lo sport con spada, fioretto e sciabola"],
        ["Sismografo","misura l'intensita' di una scossa tellurica"],
        ["Spinterogeno","nell'automobile, conduce l'alta tensione alle candele"],
        ["Sesterzi","quattro formavano un denaro"],
        ["Schubert","scrisse un quintetto ispirato alla trota"],
        ["Sangria","si ottiene mescolando vino e frutta fresca"]
    ],
    "t":[
        ["Tesoro","Chi trova un amico trova un..."],
        ["testa", "La fa perdere... la ghigliottina"],
        ["Torino","La città con il castello del Valentino"],
        ["Torino","La città con la Basilica di Superga"],
        ["Testina","era 'd'oro' nel soprannome che accumunava i calciatori Puricelli e Carlo Galli"],
        ["Traiano","fu il primo imperatore romano non di origine romana"],
        ["Tribuna politica","fu inaugurata da Mario Scelba in televisione l'11 ottobre 1960"],
        ["Trentanove","gli scalini della scala di Hitchcock"],
        ["Trimmer","il componente elettrico costituito da una resistenza variabile"],
        ["Truffaut","il Francois che ha avuto Incontri ravvicinati del terzo tipo"],
        ["Twain","il Mark che disse che smettere di fumare era facilissimo perche' lui smetteva tutti i giorni"],
        ["Turchia","il paese in cui si trovano le rovine di Troia"],
        ["Tex Willer","il personaggio che ha dato fama a Gian Luigi Bonelli"],
        ["Tintoretto","il pittore che con Il paradiso detiene il record del dipinto su tela piu' grande del mondo"],
        ["terra","il significato della radice greca 'geo'"],
        ["Tre soldi","il valore di un'Opera di Bertold Brecht"],
        ["Tennessee","il Williams drammaturgo statunitense che si ispirava alla vita del profondo sud del suo paese"],
        ["Trinidad","l'isola che e' unita a Tobago"],
        ["tognazzi","l'Ugo che e' caduto piu' volte ne Il vizietto"],
        ["Thatcher","la 'lady di ferro' che fu primo ministro inglese"],
        ["Tenera","la 'notte' di Francis Scott Fitgerald"],
        ["Tequila","la bevanda nazionale messicana"],
        ["Transiberiana","la linea ferroviaria che ha 87 stazioni su un percorso di 7.500 km."],
        ["Tedesca","la lingua nella quale e' pubblicata la rivista Stern"],
        ["Tedesco","la lingua nella quale e' pubblicata la rivista Stern"],
        ["Triumph","la moto condotta da Marlon Brando ne Il selvaggio"],
        ["Tunisia","la nazione in cui si possono visitare le rovine di Cartagine"],
        ["Trafalgar Square","la piazza che e' il centro geografico di Londra"],
        ["Temple","la Shirley che a 10 anni aveva gia' guadagnato 1 milione di dollari"],
        ["torino","la squadra di calcio distrutta nella tragedia di Superga del 1947"],
        ["Telematch","La trasmissione televisiva con la quale Enzo Tortora inizio' la sua carriera televisiva"],
        ["Tropicale","la zona che si trova tra il tropico del Cancro e quello del Capricorno"],
        ["tigna","Malattia del cuoio capelluto determinata da un fungo parassita"],
        ["Toto'","parla con gli uccelli in un film di Pasolini"],
        ["Tiberio","uno dei Gracchi"]
    ],
    "u":[
        ["Ubiquita'","Facolta' di poter essere in piu' luoghi nello stesso tempo"],
        ["Ulisse","fu trattenuto per 10 anni dalla ninfa Calipso"],
        ["Ulster","il nome dell'Irlanda del Nord"],
        ["Ungheria","la nazione che ha una capitale nata dalla fusione tra Buda e Pest"],
        ["Ungheria","nel 1956 fu vittima dell'invasione sovietica"],
        ["Ugola","pende al di sopra della lingua"]
    ],
    "v":[
        ["Vagabondo","accompagna Lilli in un film della Disney"],
        ["Verdi","compose l'opera comica Un giorno al regno"],
        ["Vaghe","cosi' erano 'le stelle dell'Orsa' del Leopardi"],
        ["vinaccioli","i semi dell'uva"],
        ["Voltaire","il nome d'arte con il quale e' conosciuto il filosofo Francois Marie Arouet"],
        ["Valentino","il Rodolfo che e' stato 'sceicco' e 'figlio dello sceicco'"],
        ["Valentino","il Rodolfo irresistibile attore italiano che mori' a 31 anni nel 1925 a Hollywood"],
        ["Valentino","il Rodolfo reso famoso da I quattro cavalieri dell'apocalisse"],
        ["Valentino","il Santo Patrono di Terni"],
        ["Vamba","L'autore de Il giornalino di Gian Burrasca"],
        ["Via col vento","l'unico romanzo di Margaret Mitchell"],
        ["Varsavia","la capitale europea sulle rive della Vistola"],
        ["Venezia","la citta' che e' soggetto prediletto del Canaletto"],
        ["Venezia","la citta' con il maggior numero di ponti"],
        ["Venezia","la citta' con il Ponte dei Sospiri"],
        ["Vienna","la citta' in cui si puo' andare a spasso nei giardini del Belvedere"],
        ["Viterbo","la citta' nella quale furono murati i cardinali"],
        ["Venezia","la piazza di Roma dove si trova il chilometro zero"],
        ["Violino","lo strumento musicale suonato da Mussolini"],
        ["Varani","sono chiamati 'draghi di Komodo'"]
    ],
    "z":[
        ["Zappa","Gino padre della contabilita' moderna"],
        ["Zeffirelli","il Franco che ha realizzato il kolossal televisivo sulla vita di Gesu' Cristo"],
        ["Zurli'","il mago interpretato in tv da Cino Tortorella"],
        ["Zenit","il punto del cielo situato sulla verticale dell'osservatore"],
        ["Zwingli","L'Ulrico che con Lutero fu l'altro protagonista della riforma"]
    ]
}